# Generated by Django 3.1.1 on 2020-09-28 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200928_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Imię')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='manager',
        ),
        migrations.DeleteModel(
            name='PetOwnership',
        ),
        migrations.AddField(
            model_name='pet',
            name='owner_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
