# Generated by Django 3.1.1 on 2020-09-29 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('users', '0003_auto_20200928_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Zwierzę',
                'verbose_name_plural': 'Zwierzęta',
            },
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pupil', 'verbose_name_plural': 'Pupile'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AddField(
            model_name='pet',
            name='gallery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.gallery', verbose_name='Galeria'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to=settings.AUTH_USER_MODEL, verbose_name='Imię właściciela'),
        ),
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='users.animal', verbose_name='Rodzaj zwierzęcia'),
        ),
    ]
