# Generated by Django 3.1.1 on 2020-09-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_auto_20191025_1852'),
        ('users', '0004_auto_20200929_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar', verbose_name='Kalendarz'),
        ),
    ]
