# Generated by Django 3.1.1 on 2020-10-05 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_name', to=settings.AUTH_USER_MODEL, verbose_name='Doktor')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_container', to='users.petcontainer', verbose_name='Imie Doktora'),
        ),
    ]
