# Generated by Django 3.1.1 on 2020-10-05 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201005_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petcontainer',
            options={'verbose_name': 'Podopieczny', 'verbose_name_plural': 'Podopieczni'},
        ),
        migrations.AddField(
            model_name='user',
            name='pupils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.petcontainer', verbose_name='Doktor'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_container', to=settings.AUTH_USER_MODEL, verbose_name='Imie Doktora'),
        ),
    ]
