# Generated by Django 3.1.1 on 2020-10-06 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Zwierzę',
                'verbose_name_plural': 'Zwierzęta',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Imię')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pet_container', to=settings.AUTH_USER_MODEL, verbose_name='Imie Doktora')),
                ('gallery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.gallery', verbose_name='Galeria')),
                ('owner_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to=settings.AUTH_USER_MODEL, verbose_name='Imię właściciela')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='animals.animal', verbose_name='Rodzaj zwierzęcia')),
            ],
            options={
                'verbose_name': 'Pupil',
                'verbose_name_plural': 'Pupile',
            },
        ),
    ]
